//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class frd_record_definition
    {
        public int RecordDefinitionId { get; set; }
        public int RecordId { get; set; }
        public string Name { get; set; }
        public int ElementId { get; set; }
        public int Sequence { get; set; }
        public int Length { get; set; }
        public Nullable<int> DecimalPlaces { get; set; }
        public bool Mandatory { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserId { get; set; }
        public Nullable<int> Line { get; set; }
    
        public virtual ed_element_definition ed_element_definition { get; set; }
        public virtual fr_record fr_record { get; set; }
    }
}
