//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ft_file_transaction
    {
        public int FileTransactionId { get; set; }
        public int FileId { get; set; }
        public int TransactionId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserId { get; set; }
    
        public virtual fd_file_definition fd_file_definition { get; set; }
        public virtual ft_transaction ft_transaction { get; set; }
    }
}
