//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ft_transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ft_transaction()
        {
            this.ft_file_transaction = new HashSet<ft_file_transaction>();
            this.ftd_transaction_definition = new HashSet<ftd_transaction_definition>();
        }
    
        public int TransactionId { get; set; }
        public string TransactionName { get; set; }
        public string Description { get; set; }
        public string HeaderTemplate { get; set; }
        public string TrailerTemplate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserId { get; set; }
        public Nullable<int> HeaderLength { get; set; }
        public Nullable<int> TrailerLength { get; set; }
        public Nullable<int> HeaderCount { get; set; }
        public Nullable<int> TrailerCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ft_file_transaction> ft_file_transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ftd_transaction_definition> ftd_transaction_definition { get; set; }
    }
}
