//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int id { get; set; }
        public string title { get; set; }
        public string overview { get; set; }
        public Nullable<double> vote_average { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
    }
}
