//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_stored_procedure
    {
        public int StoredProcedureId { get; set; }
        public string Schema { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
    }
}
